---
title: "Project 3"
author: "Zihan Ye, Yolanda Zhao"
date: "4/14/2018"
output: pdf_document
---

#Code
```{r, message=FALSE, warning=FALSE, echo=FALSE}
library(imager)
library(RColorBrewer)
library(cluster)
library(varhandle)
library(colorspace)
```

```{r,include=FALSE}
BWNeighbourCorr <- function(image,offset=2,position="left") {
  if (position=="left"|position=="right"){
    stencil <- data.frame(dx=c(0,-offset,offset),dy=c(0,0,0))
# We randomly select 500 pixels from the resized image 
    image2 <- resize(image,128,128)
    image.bw <- grayscale(image2)
    pos.x <- round(runif(500,2*offset,width(image.bw)-offset))
    pos.y <- round(runif(500,2*offset,height(image.bw)-offset))
    pos <- cbind(pos.x,pos.y)
  
    val <- alply(pos,1,function(v) get.stencil(image.bw,stencil,x=v[1],y=v[2]))
    mat <- do.call(rbind,val)
  
    cor_LeftNeighbour <- cor(mat)[1,2] # New Feature 1
    cor_RightNeighbour <- cor(mat)[1,3] # New Feature 2 
    if (position=="left"){
      return (cor_LeftNeighbour)
    }
    else{
      return (cor_RightNeighbour)
    }
  }
  
  if (position=="up"|position=="down"){
    stencil <- data.frame(dx=c(0,0,0),dy=c(0,-offset,offset))
# We randomly select 500 pixels from the resized image 
    image2 <- resize(image,128,128)
    image.bw <- grayscale(image2)
    pos.x <- round(runif(500,2*offset,width(image.bw)-offset))
    pos.y <- round(runif(500,2*offset,height(image.bw)-offset))
    pos <- cbind(pos.x,pos.y)
  
    val <- alply(pos,1,function(v) get.stencil(image.bw,stencil,x=v[1],y=v[2]))
    mat <- do.call(rbind,val)
  
    cor_DownNeighbour <- cor(mat)[1,2] # New Feature 1
    cor_UpNeighbour <- cor(mat)[1,3] # New Feature 2 
    if (position=="Up"){
      return (cor_UpNeighbour)
    }
    else{
      return (cor_DownNeighbour)
    }
  }
}
```


```{r,include=FALSE}
warmth <- function(image){
  m <- resize(image,128,128)
  
  h =rgb2hsv(matrix(c(R(m),G(m),B(m)),byrow=TRUE,nrow=3),maxColorValue = 1)[1,]*360 #calculate hues for each pixel
  
  warmth <- (length(which(h<=90)) + length(which(h>=330 & h <= 360)))/length(h) # Proportion of Warm Colored Pixels 
  
  return (warmth)
  
}
```

```{r}
colorful<-function(m){
  h =rgb2hsv(matrix(c(R(m),G(m),B(m)),byrow=TRUE,nrow=3),maxColorValue = 1)[1,]*360
  s =rgb2hsv(matrix(c(R(m),G(m),B(m)),byrow=TRUE,nrow=3),maxColorValue = 1)[2,]*360 
  v =rgb2hsv(matrix(c(R(m),G(m),B(m)),byrow=TRUE,nrow=3),maxColorValue = 1)[3,]*360 
  red<-0
  orange<-0
  yellow<-0
  green<-0
  blue<-0
  purple<-0
  black<-0
  white<-0
  gray<-0
  for(i in 1:length(h)){
    if(v[i]<=15){
      black=black+1
    } else if(v[i]>=95 & s[i] <=2){
      white=white+1
    } else if(v[i]<95 & v[i]>=35 & s[i] <=5){
      gray=gray+1
    } else if(h[i]<25|h[i]>=330){
      red<-red+1
    } else if (h[i]<50&&h[i]>=25){
      orange<-orange+1
    } else if (h[i]<70&&h[i]>=50){
      yellow<-yellow+1
    } else if (h[i]<160&&h[i]>=70){
      green<-green+1
    } else if (h[i]<250&&h[i]>=160){
      blue<-blue+1
    } else {
      purple<-purple+1
    }
  }
  threshold<-length(h)*.4
  colors <- c(red, orange, yellow, green, blue, purple, black, white, gray)
  colorNames <- c("red", "orange", "yellow", "green", "blue", "purple", "black", "white", "gray")
  if(max(colors)>threshold){
    colorResult<-colorNames[which.max(colors)]
  } else {
    colorResult<-"Colorful"
  }
  return(colorResult)
}
```

```{r, cache=TRUE}
feat<-function(m){
d = dim(m)[1:2] #get the height and width of image
m<-resize(m, ceiling(d[1]/5), ceiling(d[2]/5)) #reduce photo quality to make analysis faster
d = dim(m)[1:2] #get the height and width of image
m<-resize(m, d[1]%/%8*8, d[2]%/%8*8) #convert dimensions into the nearest multiples of 8 smaller than that dimension
d = dim(m)[1:2]

hsv =t(rgb2hsv(matrix(c(R(m),G(m),B(m)),byrow=TRUE,nrow=3),maxColorValue = 1))
h<-matrix(hsv[,1]*360,nrow=d[2],ncol=d[1],byrow=TRUE)
s<-hsv[,2]*360
v<-hsv[,3]*360

#Feature 1: Center
foo = sapply(1:8,function(j) sapply(1:8,function(i) mean(h[(i-1)*d[2]/8 + (1:d[2]/8),(j-1)*d[1]/8 + (1:d[1]/8)])))
centerDiff<-abs(mean(foo[3:6,3:6])-mean(c(foo[1:2,1:8], foo[7:8,1:8], foo[3:6,1:2], foo[3:6,7:8])))


#Feature 2: Edges
##Edges are the outer 28 boxes if the image is divided into 8x8 boxes
edges = c(foo[1:8,1], foo[1:8,8], foo[1,2:7], foo[8,2:7])
edges<-sd(edges)


#Feature 3: Value mean

valmean<-mean(v)

#Feature 4: Value variance
valvar<-var(v)

#Feature 5: Saturation mean
satmean<-mean(s)

#Feature 6: Saturation variance
satvar<-var(s)

#Feature 7: Dominance
huegroups<-kmeans(hsv,8,nstart=5)
clusinfo<-sort(table(huegroups[1]),decreasing=TRUE)
largestcluster<-as.numeric(names(clusinfo[1]))
clustersize<-as.numeric(clusinfo[1])
dominance<-clustersize/dim(hsv)[1]

#Feature 8: Left Neighbors
left<-BWNeighbourCorr(m, position="left")

#Feature 9: Up Neighbors
up<-BWNeighbourCorr(m, position="up")

#Feature 10: Warmth
warm<-warmth(m)

#Feature 11: Colorful
colorful<-colorful(m)

c(centerDiff, edges, valmean, valvar, satmean, satvar, dominance, left, up, warm, colorful)
}
```


```{r, cache=TRUE}
files = list.files('C:/Users/bfd2/Desktop/WCMA Public Thumbs',pattern = '*jpg$',full.name=TRUE) 
set.seed(1)
samp = sample(files,500)

features<-matrix(nrow=500,ncol=11)
results<-cbind(samp,features)
colnames(results)<-c("Image", "Center", "Edges", "Value Mean", "Value Variance", "Saturation Mean", "Saturation Variance", "Dominance", "Left Neighbor", "Up Neighbor", "Warmth", "Colorful?")
for(i in 1:500){
m <- load.image(samp[i])
x<-feat(m)
results[i,2]<-as.numeric(x[1])
results[i,3]<-as.numeric(x[2])
  results[i,4]<-as.numeric(x[3])
  results[i,5]<-as.numeric(x[4])
  results[i,6]<-as.numeric(x[5])
  results[i,7]<-as.numeric(x[6])
  results[i,8]<-as.numeric(x[7])
  results[i,9]<-as.numeric(x[8])
  results[i,10]<-as.numeric(x[9])
  results[i,11]<-as.numeric(x[10])
  results[i,12]<-x[11]
}
```

```{r}
results2<-unfactor(results[,2:11])
results3<-matrix(results2,nrow=500,ncol=500)
results4<-as.numeric(results3[,1:10])
results5<-matrix(results4,nrow=500,ncol=10)


complexity<-cbind(results5[,4], results5[,6:9])
personality<-cbind(results5[,3], results5[,5],results5[,10])
centrality<-results5[,1:2]
```


```{r}
#clustering algorithm for the complexity feature set
dismat<-daisy(complexity,metric='manhattan', stand=TRUE)
plot(2:20, sapply(2:20, function(k) mean(silhouette(kmeans(complexity, k)$cluster, dismat)[, 3])), type = "b", ylab = "Avg Silhouette", xlab = "K")
clustalgo1<-kmeans(complexity, 5, nstart = 5)
```

```{r}
dismat<-daisy(personality,metric='manhattan', stand=TRUE)
plot(2:20, sapply(2:20, function(k) mean(silhouette(kmeans(personality, k)$cluster, dismat)[, 3])), type = "b", ylab = "Avg Silhouette", xlab = "K")
clustalgo2<-kmeans(personality, 6, nstart = 5)
```

```{r}
dismat<-daisy(centrality,metric='manhattan', stand=TRUE)
plot(2:20, sapply(2:20, function(k) mean(silhouette(kmeans(centrality, k)$cluster, dismat)[, 3])), type = "b", ylab = "Avg Silhouette", xlab = "K")


clustalgo3<-kmeans(centrality, 2, nstart = 5)
#do this three times, figure out column names


```


```{r}
final<-cbind(results[,1],results5, clustalgo1$cluster, clustalgo2$cluster, clustalgo3$cluster, results[,12])


colnames(final)<-c("Image", "Center", "Edges", "Value Mean", "Value Variance", "Saturation Mean", "Saturation Variance", "Dominance", "Left Neighbor", "Up Neighbor", "Warmth", "Complexity Clusters", "Personality Clusters", "Centrality Clusters", "Colorful?")


write.csv(final, file="results.csv")

```

```{r}
#x is a list of indices
composite<-function(x){
  rValues <- sapply(x,function(i) {R(resize(load.image(samp[i]),128,128))})
  gValues <- sapply(x,function(i) {G(resize(load.image(samp[i]),128,128))})
  bValues <- sapply(x,function(i) {B(resize(load.image(samp[i]),128,128))})
  
  rMean <- apply(rValues,1,mean)
  gMean <- apply(gValues,1,mean)
  bMean <- apply(bValues,1,mean)
  
  plot(as.cimg(c(rMean,gMean,bMean)), axes=FALSE)
}
```



```{r}
lapply(unique(as.numeric(final[,12])),function(x){composite(which(as.numeric(final[,12])==x))})
```

```{r}
lapply(unique(as.numeric(final[,13])),function(x){composite(which(as.numeric(final[,13])==x))})
```

```{r}
lapply(unique(as.numeric(final[,14])),function(x){composite(which(as.numeric(final[,14])==x))})
```

