---
title: "Final Project"
author: "Yolanda"
date: "April 30, 2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(shiny)
require(maps)
require(dplyr)
require(ggplot2)


```

```{r}

ref <- read.csv("/Users/Yolanda/Desktop/Williams/2018S/STAT442_2018/Project 3/wcma-collection.csv",stringsAsFactors = FALSE)
raw <- ref

files = list.files("/Users/Yolanda/Desktop/Williams/2018S/STAT442_2018/Project 3/WCMA Public Thumbs",pattern = '*jpg$',full.name=TRUE) 
#set.seed(1)
#samp = sample(files,500)

filenames = list.files("/Users/Yolanda/Desktop/Williams/2018S/STAT442_2018/Project 3/WCMA Public Thumbs",pattern = '*jpg$',full.name=FALSE) 
#set.seed(1)
#sampNames = sample(filenames,500)



#Find repeats

## Dealing with Prendergast 
prendergast <-ref[ref$classification=="WCMA-Prendergast",]

prendDrawing <- grep("watercolor",prendergast$object_name)
prendPainting <- grep("painting",prendergast$object_name)
prendPrint <- grep("print",prendergast$object_name)
prendPhoto <- grep("photo",prendergast$object_name)

prendergast[prendDrawing,]$classification <-"WCMA-DRAWING"
prendergast[prendPainting,]$classification <-"WCMA-PAINTING"
prendergast[prendPrint,]$classification <-"WCMA-PRINTS"
prendergast[prendPhoto,]$classification <-"WCMA-PHOTO"


ref2 <- ref[-which(ref$classification=="WCMA-Prendergast"),]
ref <- rbind(ref2,prendergast)
write.csv(ref,file="newFullwcma.csv")
```

```{r}

ref <- ref[!duplicated(ref$filename), ]

remove <- c("WCMA-DEC ARTS","WCMA Reserve Collection","WCMA-WALLS","WCMA-Prendergast","WCMA-PACIFIC")
removeRows <-ref[ref$classification %in%remove,]

removeNames <- removeRows$filename

#for (i in removeNames){
  #file.remove(paste0("/Users/Yolanda/Desktop/Williams/2018S/STAT442_2018/Project 3/WCMA Public Thumbs/",i))
#}

#files2 <- list.files("/Users/Yolanda/Desktop/Williams/2018S/STAT442_2018/Project 3/WCMA Public Thumbs")

ref <- ref[!ref$classification%in%remove,]

#write.csv(ref,"newRef.csv")

classCounts <- table(ref$classification)
require(ggplot2)

ggplot(ref, aes(classification))+ geom_bar() +coord_flip() + ggtitle("Number of Images in WCMA collection by Category")
#+ theme(axis.text.x = element_text(angle = 90, hjust = 1))
```


```{r}



```

```{r}


#keep<-c("title","maker","classification","creation date","accession_date","medium","filename")
#keep<-c(3,4,7,10,13,15,16,26)
#important<-ref.sample[,keep]
#data <- data.frame(final)



#data$Image <- gsub("/Users/Zihanye 1/Desktop/WCMA Public Thumbs/","",data$Image)

#data$filename <- data$Image
#combined<-inner_join(data,important,by="filename")
#combined <- read.csv("/Users/Yolanda/Desktop/Williams/2018S/STAT442_2018/Project 3/combined.csv")


```

```{r}
# Define UI for application that draws a histogram
ui <- fluidPage(
  # Application title
  titlePanel("WCMA Collection"),
  plotOutput("plot"),
  hr(),
  
  fluidRow(
    column(width=2,
           h4("Pick Your Personality")
           ,
           selectInput('year', "Medium:", list("Wild Forest"=1, "Sunday on a Spring"=2))
           ),
    column(width=1,imageOutput("Person1")),
    column(width=1,imageOutput("Person2"))
    #render images of clusters here
),

  fluidRow(
    column(3,
           h4("Pick Your Color")
           ,
           selectInput('year', "Medium:", list("Sunrise Orange"=1, "very Blue"=2))
           ),
    column(width=1,imageOutput("Color1")),
    column(width=1,imageOutput("Color2"))
),
     
  fluidRow(column(4, offset=1,
                  selectInput('year', "Medium:", list("Drawing"="WCMA-DRAWING",
                                                      "Sculpture"="WCMA-SCULPTURE", 
                                                      "Ancient"="WCMA-ANCIENT",
                                                      "Amerindian"="WCMA-AMERINDIAN",
                                                      "Prints"="WMCA-PRINTS",
                                                      "Painting"="WCMA-PAINTING",
                                                      "Eastern"="WCMA-EASTERN",
                                                      "African"="WCMA-AFRICAN",
                                                      "Pacific"="WCMA-PACIFIC",
                                                      "Photo"="WCMA-PHOTO")),
                  
                  sliderInput("complexity", "Complexity:",
                              min = 1, max = 10,
                              value = 5),
                  
                  actionButton("finish", "Recommend Me Something")             
  )
  )
)


# Define server logic required to draw a histogram
server <- function(input, output) {
  

output$Person1 <- renderImage({
    filename = normalizePath(file.path("10_1 copy.jpg"))
    list(src = filename,width="100px")
  }, deleteFile = FALSE)
  
  output$Person2 <- renderImage({
    filename = normalizePath(file.path("16_1 copy.jpg"))
    list(src = filename,width="100px")
  }, deleteFile = FALSE)

 output$Color1 <- renderImage({
    filename = normalizePath(file.path("20_1_4_a copy.jpg"))
    list(src = filename,width="100px")
  }, deleteFile = FALSE)

 output$Color2 <- renderImage({
    filename = normalizePath(file.path("20_1_4_a copy.jpg"))
    list(src = filename,width="100px")
  }, deleteFile = FALSE)

}

# Run the application 
shinyApp(ui = ui, server = server)

```

